### ISSUE TITLE
py.test ImportMismatchError failure

### ISSUE THREAD

**Issue by abadger** [jaraco/jaraco.collections#1]
== tldr; ==

When running python setup.py pytest I get this error:

```
====================================================== ERRORS =======================================================
______________________________________ ERROR collecting jaraco/collections.py _______________________________________
/usr/lib/python2.7/site-packages/py/_path/local.py:668: in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
E   ImportMismatchError: ('jaraco.collections', '/usr/lib/python2.7/site-packages/jaraco/collections.py', local('/srv/git/irclib-update/python-jaraco-collections/jaraco.collections-1.3.1/jaraco/collections.py'))
========================================= 1 passed, 1 error in 0.04 seconds =========================================
```

It seems to be triggered by having a version of jaraco.collections (in this case, the same version as I'm trying to build) installed and attempting to run the test suite in the source.

== Little more info ==

jaraco.collections and jaraco.text have a dependency on each other.  So the distro package for jaraco.text that I've built Requires: jaraco.collections.  This pulls in the distro package of jaraco.collections.  For someone installing the packages on a system this works fine.

When I want to run the test suite from within a package build of jaraco.collections I need to have the dependencies of the packages installed.  So I list jaraco.text as a BuildRequires.  This installs the distro package of jaraco.text (good!) but since that requires jaraco.collections, the distro package of jaraco.collections is also installed.

Then when I run the tests via pytest, pytest finds both the distro package and the local package and emits that ImportMismatchError.

I'm not sure why pytest is finding both versions -- I've tried setting PYTHONPATH to the directory I'm building jaraco.collections in to try to have the local version picked up first but that has no effect.  I have found an ugly, ugly workaround which I'm using to build and test the package for now: in the toplevel directory,

```
mv jaraco/ j/
python2 setup.py pytest
mv j/ jaraco/
```

I'd love to get rid of that hack but I'm not sure what py.test is really complaining about or how to really fix it.

**Comment by abadger** [comment]
Note -- this also affects jaraco.text.  But the report would be a duplicate of this so I didn't want to both er you with it twice :-)

**Comment by jaraco** [comment]
I've encountered this as well when running tests in continuous integration. I probably don't encounter it locally because I usually have to run `setup.py develop` before running tests anyway to avoid conflicts with the package installed in system site-packages.

I think what it comes down to is that pytest-runner, which is resolving the dependencies using easy_install, doesn't recognize that the package under test is available, so downloads it instead. I don't yet have a solution, so whatever hack you have in place will have to suffice until a solution can be devised.

I suspect this issue affects any package using `pytest-runner` or the canonical `setup.py test` and where there's a circular dependency. Circular dependencies are rare among packages, so perhaps the solution would be to factor out that circular dependency. Better would be for the package resolver to do the right thing here.

**Comment by abadger** [comment]
<nod> Note that I can reproduce that error with py.test as well:

```
$ py.test           (13:13:21)
================================================ test session starts ================================================
platform linux2 -- Python 2.7.10, pytest-2.8.5, py-1.4.30, pluggy-0.3.1
rootdir: /srv/git/irclib-update/python-jaraco-collections/jaraco.collections-1.3.1, inifile: pytest.ini
collected 1 items / 1 errors 

tests/test_collections.py .

====================================================== ERRORS =======================================================
______________________________________ ERROR collecting jaraco/collections.py _______________________________________
/usr/lib/python2.7/site-packages/py/_path/local.py:668: in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
E   ImportMismatchError: ('jaraco.collections', '/usr/lib/python2.7/site-packages/jaraco/collections.py', local('/srv/git/irclib-update/python-jaraco-collections/jaraco.collections-1.3.1/jaraco/collections.py'))
========================================= 1 passed, 1 error in 0.07 seconds =========================================
```
