### ISSUE TITLE
Misreference to six

### ISSUE THREAD

**Issue by GreenWolf13** [jaraco/jaraco.collections#2]
When using your python irc libraries, the following error occurs when importing irc.bot:

`Traceback (most recent call last):
  File "bot.py", line 1, in <module>
    import irc.bot
  File "/usr/local/lib/python2.7/dist-packages/irc/bot.py", line 22, in <module>
    from .dict import IRCDict
  File "/usr/local/lib/python2.7/dist-packages/irc/dict.py", line 4, in <module>
    from jaraco.collections import KeyTransformingDict
  File "/usr/local/lib/python2.7/dist-packages/jaraco/collections.py", line 755, in <module>
    class InstrumentedDict(six.moves.UserDict):
AttributeError: '_MovedItems' object has no attribute 'UserDict'
`

This appears to be caused by an error in how InstrumentedDict subclasses six.moves.UserDict

**Comment by jaraco** [comment]
Is it possible you have an old version of six?

Looking at the [code for six 1.7.0](https://bitbucket.org/gutworth/six/src/35f6d89f826f63486214e4746af028ccaa088901/six.py?at=1.7.0&fileviewer=file-view-default#six.py-233), which is the [minimum version required by jaraco.collections](https://github.com/jaraco/jaraco.collections/blob/master/setup.py#L42), I see the UserDict is declared and present.
